---
title: "Final Project Musings"
author: "Evan Solomon"
date: "11/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(readr)
library(stringr)
library(lubridate)
```

# Note: The 2015 running of the 10 mile race had to be cut short and had a total distance of 9.39 miles.
format for printing: sprintf("%02d:%02d:%02d", hour(test), minute(test), second(test))
drop nas before analysis: raw_runner_data %>% drop_na(c("Name","Sex","Age","Time","Pace", "PiS/TiS"))

```{r}
setwd("/Users/evanlsolomon/environment/RProjects/biostatistics/final_project/")
runner_data <- read_csv("./20211117_220140_clean-anonymized-runner-data.csv", col_types = cols(
  ID = col_integer(),
  race_year = col_integer(),
  race_type = col_factor(),
  Sex = col_factor(),
  Age = col_integer(),
  imputedAge = col_integer(),
  Time = col_character(),
  imputed_time = col_time(format = ""),
  Pace = col_time(format = ""),
  `PiS/TiS` = col_character(),
  Division = col_character(),
  `PiD/TiD` = col_character(),
  Hometown = col_character(),
  city = col_character(),
  state = col_character(),
  country_1 = col_character(),
  country_2 = col_character(),
  races_run = col_integer()
))

runner_data <- runner_data %>% mutate(minutes = as.numeric(as.duration(imputed_time), "minutes"), .after = "imputed_time")
runner_data <- runner_data %>% select(-Age, -Time, -country_2, -Hometown, -imputed_time, -Pace)
hist(runner_data$imputedAge)
hist(runner_data$minutes)
```

Figure out how to fix the time input formatting and exceptions



